class _BotCommands:
    def __init__(self):
        self.StartCommand = 'laura'
        self.MirrorCommand = 'zap'
        self.UnzipMirrorCommand = 'unzap'
        self.TarMirrorCommand = 'tarzap'
        self.CloneCommand = 'cl'
        self.CountCommand = 'count'
        self.CancelMirrorCommand = 'kill'
        self.CancelAllCommand = 'terminate'
        self.ListCommand = 'la'
        self.StatusCommand = 'statuszap'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'init'
        self.UnAuthorizeCommand = 'unauth'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'pingzap'
        self.RestartCommand = 'sleep'
        self.StatsCommand = 'statslaura'
        self.HelpCommand = 'helplaura'
        self.LogCommand = 'loglaura'
        self.SpeedCommand = 'zaptest'
        self.WatchCommand = 'stream'
        self.TarWatchCommand = 'tarstream'
        self.DeleteCommand = 'rem'
        self.UsageCommand = 'usagelaura'
        self.RepoCommand = 'repo'
        self.OwnerCommand = 'owner'
        self.ConfigCommand = 'config'

BotCommands = _BotCommands()
